spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:test
#    url: jdbc:h2:file:C:\Users\Aleksey\IdeaProjects\customer_gradle\src\main\resources\data

    jpa:
      hibernate:
        ddl-auto: create
#      properties:
#        hibernate:
#          format_sql: true
    h2:
      console:
        enabled: true
        path: /h2